### ISSUE TITLE
Fix request: fix previous visit sequence bug

### ISSUE THREAD

**Issue by 1wes** [nrf-mamas-hub/mamashub-web#34]
## Description
On the developmental milestones form, once the form is submitted, the system creates a visit for that particular encounter. The first encounter is supposed to count as visit 1, the second one as visit 2 and so on. However, in this case, the system inverses the visits, i.e the latest visit is counted as visit 1 while the very first visit is counted as visit n (with n being the total number of encounters so far). Essentially, the last encounter is labelled as visit 1 while the first encounter is labelled visit last. 

## Steps to reproduce
- Ensure you have the latest changes pulled from the `hackathon` branch.
- Once the app is running (if app not set up, check the `README` file [here](https://github.com/nrf-mamas-hub/mamashub-web), navigate to `http://localhost:3000/developmental-milestones`, click "Add Visit", and fill the form. 
- Fill the form more than once, and check the preview per listed visit.

## Possible solution
Check the retrieval and display process of developmental milestones encounters.

If you need additional info, reach out to @1wes

**Comment by malikrohail** [comment]
can i fix it

**Comment by 1wes** [comment]
Hello @malikrohail, have a go at it. I'll assign it to you

**Comment by 1wes** [comment]
Fixed the issue. You can check [this](https://github.com/nrf-mamas-hub/mamashub-web/pull/39) PR. Thanks @malikrohail for your interest in working on this.

**Comment by 1wes** [comment]
Will close this now
